name = "Arianna"
uuid = "17c2f236-ed37-45c0-bff7-21ff0c2ec05e"
version = "1.0.0-DEV"
authors = ["Matt Graham", "Ross Ah-Weng", "Callum Lau", "Anees Hussain", "Jordan Simbananiye and contributors"]

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
AbstractMCMC = "5.10.0"
Distributions = "0.25.122"
JuliaFormatter = "2.2.0"
LinearAlgebra = "1.12.0"
LogDensityProblems = "2.2.0"
PDMats = "0.11.36"
Plots = "1.41.1"
Random = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
